### ISSUE TITLE
Demo of nodejs working?

### ISSUE THREAD

**Issue by dustingetz** [arichiardi/fig-boot-reload#1]
I believe this is supposed to work with node, i attempted to reproduce this and failed, here is my attempt

https://github.com/dustingetz/cljs-node-reload-demo

After the target dir is successfully written, I can "cd target/node; node preamble.js" to successfully start the app, but no code changes are detected. The browser task does pick up changes and successfully push them to browser.

**Comment by dustingetz** [comment]
I think this is related to "FSEventStreamStart: register_with_server" warning; `rm -r ~/.boot/cache` fixed it and now it works fine.

**Comment by arichiardi** [comment]
Cool thanks for reporting AND finding a solution!

**Comment by dustingetz** [comment]
Also, `boot watch` triggered the same error in my real (much larger) project, clearing the boot cache did not resolve that one, but it came down to node_modules being under a :resource-paths, which is monitored by `boot watch`.

**Comment by arichiardi** [comment]
Maybe related https://github.com/boot-clj/boot/issues/641
